application: reddit-grammar
version: 1
runtime: python27
api_version: 1
threadsafe: true
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: 10ms

handlers:
# Backend
# Bot events
- url: /do/(post|simulate|session)
  script: main.app
  login: admin

# Warmup
- url: /_ah/warmup
  script: main.app
  login: admin

inbound_services:
- warmup